---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: Build and test front end
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.3.0a
    environment:
      CI: false
    commands:
      - cd react
      - pwd && npm install
      - pwd && npm run build
      - pwd && npm run test-ci
    when:
      event:
        - push

  - name: Copy front end to resources
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - pwd && rm -rf ./src/main/resources/frontend
      - pwd && mv ./react/build ./src/main/resources/frontend
    when:
      event:
        - push
    depends_on:
      - Build and test front end

  - name: Unit tests
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - /root/entrypoint.sh
      - sbt -mem 2048 test
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
    when:
      event:
        - push
    depends_on:
      - Copy front end to resources

  - name: Build docker image
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - /root/entrypoint.sh
      - sbt docker:stage
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
    when:
      event:
        - push
    depends_on:
      - Unit tests

  - name: Publish app
    image: plugins/ecr
    environment:
      AWS_REGION: eu-west-2
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      repo: drt/drt-dashboard
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      tags:
        - B${DRONE_BUILD_NUMBER}
        - latest
    when:
      event:
        - push
    depends_on:
      - Build docker image
      - Copy front end to resources

  - name: Code coverage report
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - /root/entrypoint.sh
      - sbt -mem 4096 --error coverage test | true
      - sbt coverageReport
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
      ENV_LOG_LEVEL: ERROR
    when:
      event:
        - push
      branch:
        - leader
    depends_on:
      - Unit tests

  - name: Scapegoat
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - /root/entrypoint.sh
      - sbt scapegoat | true
    environment:
      NVD_BASE_URL: http://nvdmirror:8008
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
      ENV_LOG_LEVEL: ERROR
    when:
      event:
        - push
      branch:
        - leader
    depends_on:
      - Code coverage report

  - name: Dependency check
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - /root/entrypoint.sh
      - sbt -mem 4096 dependencyCheck
    environment:
      NVD_BASE_URL: http://nvdmirror:8008
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
      ENV_LOG_LEVEL: ERROR
    when:
      event:
        - push
      branch:
        - leader
    depends_on:
      - Scapegoat

  - name: Sonar scanner
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/sonar-scanner:v4.6
    commands:
      - sonar-scanner -Dsonar.projectVersion=B${DRONE_BUILD_NUMBER} -X
    environment:
      DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
    when:
      event:
        - push
      branch:
        - leader
    depends_on:
      - Dependency check

  - name: Slack notification
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: devs
      template: "*{{repo.name}}: _{{build.status}}_*\nCompleted build *{{build.number}}* after *{{since build.started}}* on *{{build.branch}}*\n{{build.link}}\n"
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status:
        - success
        - failure
      event:
        - push
    depends_on:
      - Publish app
      - Unit tests

services:
  - name: NVD mirror service
    image: sspringett/nvdmirror
    ports:
      - 8008
...
